"""
Tests for Task 1.4: FFmpeg frame extraction.

All tests use synthetic videos generated by conftest.py fixtures so no
real footage is required.
"""
from pathlib import Path

import pytest
from PIL import Image

from app.worker.frame_extractor import FrameExtractionResult, extract_frames


# ---------------------------------------------------------------------------
# Basic extraction — 30fps source
# ---------------------------------------------------------------------------


def test_extract_frames_returns_result_type(synthetic_video_30fps, tmp_path):
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"))
    assert isinstance(result, FrameExtractionResult)


def test_frame_count_matches_fps_times_duration(synthetic_video_30fps, tmp_path):
    """
    For a 3s 30fps video the extractor should produce 30 × 3 = 90 frames (±1).
    """
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"))
    expected = int(result.fps * result.duration_seconds)
    assert abs(result.total_frames - expected) <= 1, (
        f"Expected ~{expected} frames, got {result.total_frames}"
    )


def test_frame_paths_are_sorted_and_exist(synthetic_video_30fps, tmp_path):
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"))
    assert len(result.frame_paths) > 0
    for p in result.frame_paths:
        assert Path(p).exists(), f"Frame file missing: {p}"
    # Paths should already be sorted (frame_00001.png < frame_00002.png …)
    assert result.frame_paths == sorted(result.frame_paths)


def test_output_pngs_are_valid_images(synthetic_video_30fps, tmp_path):
    """Each extracted file must open as a valid image with non-zero dimensions."""
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"))
    for p in result.frame_paths[:5]:  # spot-check first 5
        img = Image.open(p)
        assert img.width > 0 and img.height > 0


def test_metadata_fps_and_duration(synthetic_video_30fps, tmp_path):
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"))
    assert abs(result.fps - 30.0) < 1.0
    assert abs(result.duration_seconds - 3.0) < 0.5


def test_metadata_resolution(synthetic_video_30fps, tmp_path):
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"))
    assert result.resolution == (320, 240)


# ---------------------------------------------------------------------------
# Target FPS downsampling
# ---------------------------------------------------------------------------


def test_target_fps_downsamples_frame_count(synthetic_video_30fps, tmp_path):
    """Requesting target_fps=15 should halve the frame count compared to 30fps."""
    result = extract_frames(synthetic_video_30fps, str(tmp_path / "frames"), target_fps=15)
    assert result.fps == 15.0
    expected = int(15 * result.duration_seconds)
    assert abs(result.total_frames - expected) <= 1


# ---------------------------------------------------------------------------
# Slow-mo auto-downsampling (120fps → 30fps)
# ---------------------------------------------------------------------------


def test_slowmo_auto_downsampled_to_30fps(synthetic_video_120fps, tmp_path):
    """
    A 120fps source with no target_fps should be auto-downsampled to 30fps.
    Frame count should reflect 30fps × 3s = ~90 frames.
    """
    result = extract_frames(synthetic_video_120fps, str(tmp_path / "frames"))
    assert result.fps == 30.0, f"Expected 30.0 fps, got {result.fps}"
    expected = int(30 * result.duration_seconds)
    assert abs(result.total_frames - expected) <= 1


def test_slowmo_explicit_fps_respected(synthetic_video_120fps, tmp_path):
    """When target_fps is given explicitly it takes precedence over the auto rule."""
    result = extract_frames(synthetic_video_120fps, str(tmp_path / "frames"), target_fps=60)
    assert result.fps == 60.0


# ---------------------------------------------------------------------------
# Duration validation
# ---------------------------------------------------------------------------


def test_rejects_video_longer_than_max_duration(synthetic_video_too_long, tmp_path):
    """A 35s video must raise ValueError (default limit is 30s)."""
    with pytest.raises(ValueError, match="exceeds"):
        extract_frames(synthetic_video_too_long, str(tmp_path / "frames"))


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_raises_on_nonexistent_file(tmp_path):
    with pytest.raises(RuntimeError):
        extract_frames("/nonexistent/path/video.mp4", str(tmp_path / "frames"))
