"""create analyses table

Revision ID: fb5f0496c976
Revises: 
Create Date: 2026-03-26 22:33:57.558862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5f0496c976'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('stroke_type', sa.Enum('forehand', 'backhand_one', 'backhand_two', 'serve_flat', 'serve_kick', 'serve_slice', 'volley', name='stroketype'), nullable=False),
    sa.Column('video_s3_key', sa.String(length=512), nullable=False),
    sa.Column('pro_reference', sa.String(length=255), nullable=False),
    sa.Column('pose_data', sa.JSON(), nullable=True),
    sa.Column('phase_scores', sa.JSON(), nullable=True),
    sa.Column('deviations', sa.JSON(), nullable=True),
    sa.Column('coaching_feedback', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
